{
  "version": "3",
  "services": {
    "router1": {
      "build": {
        "context": ".",
        "dockerfile": "Dockerfile"
      },
      "container_name": "router1",
      "volumes": [
        "vol_router1:/dados",
        "./grafos:/app/grafos"
      ],
      "networks": {
        "lan_1": {
          "ipv4_address": "172.101.0.1"
        },
        "wan_1_1": {
          "ipv4_address": "172.1.1.1"
        }
      },
      "command": "python src/roteador.py --meu_ip 172.101.0.1 --lan 172.101.0.10 172.101.0.11 --wan '{\"172.1.1.1\": [\"172.1.1.2\"]}'"
    },
    "host1_1": {
      "build": {
        "context": ".",
        "dockerfile": "Dockerfile"
      },
      "container_name": "host1_1",
      "networks": {
        "lan_1": {
          "ipv4_address": "172.101.0.10"
        }
      },
      "stdin_open": true,
      "tty": true,
      "command": "python src/host.py 172.101.0.10 172.101.0.1"
    },
    "host1_2": {
      "build": {
        "context": ".",
        "dockerfile": "Dockerfile"
      },
      "container_name": "host1_2",
      "networks": {
        "lan_1": {
          "ipv4_address": "172.101.0.11"
        }
      },
      "stdin_open": true,
      "tty": true,
      "command": "python src/host.py 172.101.0.11 172.101.0.1"
    },
    "router2": {
      "build": {
        "context": ".",
        "dockerfile": "Dockerfile"
      },
      "container_name": "router2",
      "volumes": [
        "vol_router2:/dados",
        "./grafos:/app/grafos"
      ],
      "networks": {
        "lan_2": {
          "ipv4_address": "172.102.0.1"
        },
        "wan_1_1": {
          "ipv4_address": "172.1.1.2"
        },
        "wan_2_1": {
          "ipv4_address": "172.2.1.1"
        }
      },
      "command": "python src/roteador.py --meu_ip 172.102.0.1 --lan 172.102.0.10 172.102.0.11 --wan '{\"172.1.1.2\": [\"172.1.1.1\"], \"172.2.1.1\": [\"172.2.1.2\"]}'"
    },
    "host2_1": {
      "build": {
        "context": ".",
        "dockerfile": "Dockerfile"
      },
      "container_name": "host2_1",
      "networks": {
        "lan_2": {
          "ipv4_address": "172.102.0.10"
        }
      },
      "stdin_open": true,
      "tty": true,
      "command": "python src/host.py 172.102.0.10 172.102.0.1"
    },
    "host2_2": {
      "build": {
        "context": ".",
        "dockerfile": "Dockerfile"
      },
      "container_name": "host2_2",
      "networks": {
        "lan_2": {
          "ipv4_address": "172.102.0.11"
        }
      },
      "stdin_open": true,
      "tty": true,
      "command": "python src/host.py 172.102.0.11 172.102.0.1"
    },
    "router3": {
      "build": {
        "context": ".",
        "dockerfile": "Dockerfile"
      },
      "container_name": "router3",
      "volumes": [
        "vol_router3:/dados",
        "./grafos:/app/grafos"
      ],
      "networks": {
        "lan_3": {
          "ipv4_address": "172.103.0.1"
        },
        "wan_2_1": {
          "ipv4_address": "172.2.1.2"
        }
      },
      "command": "python src/roteador.py --meu_ip 172.103.0.1 --lan 172.103.0.10 172.103.0.11 --wan '{\"172.2.1.2\": [\"172.2.1.1\"]}'"
    },
    "host3_1": {
      "build": {
        "context": ".",
        "dockerfile": "Dockerfile"
      },
      "container_name": "host3_1",
      "networks": {
        "lan_3": {
          "ipv4_address": "172.103.0.10"
        }
      },
      "stdin_open": true,
      "tty": true,
      "command": "python src/host.py 172.103.0.10 172.103.0.1"
    },
    "host3_2": {
      "build": {
        "context": ".",
        "dockerfile": "Dockerfile"
      },
      "container_name": "host3_2",
      "networks": {
        "lan_3": {
          "ipv4_address": "172.103.0.11"
        }
      },
      "stdin_open": true,
      "tty": true,
      "command": "python src/host.py 172.103.0.11 172.103.0.1"
    }
  },
  "networks": {
    "lan_1": {
      "ipam": {
        "config": [
          {
            "subnet": "172.101.0.0/24",
            "gateway": "172.101.0.254"
          }
        ]
      }
    },
    "wan_1_1": {
      "ipam": {
        "config": [
          {
            "subnet": "172.1.1.0/24",
            "gateway": "172.1.1.254"
          }
        ]
      }
    },
    "lan_2": {
      "ipam": {
        "config": [
          {
            "subnet": "172.102.0.0/24",
            "gateway": "172.102.0.254"
          }
        ]
      }
    },
    "wan_2_1": {
      "ipam": {
        "config": [
          {
            "subnet": "172.2.1.0/24",
            "gateway": "172.2.1.254"
          }
        ]
      }
    },
    "lan_3": {
      "ipam": {
        "config": [
          {
            "subnet": "172.103.0.0/24",
            "gateway": "172.103.0.254"
          }
        ]
      }
    }
  },
  "volumes": {
    "vol_router1": {},
    "vol_router2": {},
    "vol_router3": {}
  }
}
